### ISSUE TITLE
Compatibility Issue Between django-jazzmin and django-admin-site-search

### ISSUE THREAD

**Issue by talebSleiman** [ahmedaljawahiry/django-admin-site-search#24]
When using django-jazzmin and django-admin-site-search together, a critical compatibility issue arises, impacting the functionality and user experience of the Django admin interface. Notably, the search button is missing from the admin panel, depriving users of essential navigation tools, while attempts to initiate search via `ctrl + k` result in layout distortions within the django-admin-site-search interface, impeding readability and usability.

**Comment by ahmedaljawahiry** [comment]
Can't say I've ever used [django-jazzmin](https://github.com/farridav/django-jazzmin) but, at a glance, I'm not surprised. The templates here assume the default Django admin, otherwise it's down to you to tweak things as required. 

In the end, there's a view and a couple of templates that need inserting _somewhere_ in your admin site. I'd try to extend `jazzmin`'s admin and see if it's possible to add [these](https://github.com/ahmedaljawahiry/django-admin-site-search/blob/main/README.md#3-add-templates) templates somewhere that has little impact on the rest of the site. Worst case scenario, you could re-implement the html/JS in a way that fits in with `jazzmin`.  

If there's any general changes that would make things easier to customise, let me know 🙏
