### ISSUE TITLE
Objects show up multiple times

### ISSUE THREAD

**Issue by WillNilges** [ahmedaljawahiry/django-admin-site-search#41]
_Amazing_ plugin. Thank you for authoring this.

I'm working on [implementing this in my app](https://github.com/nycmeshnet/meshdb/pull/776) and noticed a small issue: When I search for certain things from the homescreen, sometimes the results are "duplicated".

This screenshot was taken with the basic configuration (I believe "model_char_fields")

![image](https://github.com/user-attachments/assets/d7ba9a66-a42e-4073-a5cb-41fae84fbf41)

When I switched to "admin_search_fields", the problem remained, but the duplication is less bad: 
![image](https://github.com/user-attachments/assets/19107458-9404-42a8-a679-73b4f95f4e33)

It appears to be inconsistent, though, depending on what page you are viewing. All of these links go to the same place.

![image](https://github.com/user-attachments/assets/c9155493-b11f-409b-bcb3-75c363ac1d28)

**Comment by ahmedaljawahiry** [comment]
Hi! Glad you like the package, and thanks for raising the issue.

Weird one! I've had a quick look at your PR and the setup all looks fine. 

My first instinct is that it's a UI bug, because the counts (`Showing 1 app, 1 model, and 1 object`) vary so drastically from the results. A quick way to verify this is to look at the network tab, in your browser dev tools, while searching:

![image](https://github.com/user-attachments/assets/9331800b-850e-4d43-9d02-de444282fd7e)

Do the results there match what is shown in the UI?

If that's all good, i wonder if it's the fact that you're using the "Django simple history" package. I'll try to get it running locally at some point and see 🙏

**Comment by WillNilges** [comment]
Update for you: Seems like this is actually a known issue with our application 😅 There's some hacky stuff going on with our Admin UI. We're running it as a single-page application, sort of. We have this custom-built map widget that runs side-by-side, and through some somewhat cursed javascript we have achieved this, but there are problems because Django expects full page reloads often.

This is aforementioned cursed javascript.
https://github.com/nycmeshnet/meshdb/blob/main/src/meshweb/static/admin/map.js#L193-L221

And we actually have an issue open about this: https://github.com/nycmeshnet/meshdb/issues/631

Sorry for the false report! Problem is actually on our side 😄 

Now, as for what to do about it, that's an open question. Perhaps we could do it by running the admin UI in one iframe, the map in another iframe, and somehow communicate between them? Perhaps we could find a way to keep all the javascript loaded. But that's a conversation for another ticket ;)

**Comment by ahmedaljawahiry** [comment]
Thanks for the update! 

Glad you got to the bottom of it, and good luck with the fix 🙏
